### ISSUE TITLE
deployment of v4.3.3 on corefacility

### ISSUE THREAD

**Issue by kevinkle** [superphy/backend#159]

**Comment by kevinkle** [comment]
Running Blazegraph on host, via `screen` and inside `/Warehouse/Users/claing/superphy/spfy/docker-blazegraph/2.1.4` - the `bigdata.jnl` will be stored there.

`java -server -Xmx4g -Dbigdata.propertyFile=/Warehouse/Users/claing/superphy/spfy/docker-blazegraph/2.1.4/RWStore.properties -jar blazegraph.jar`

**Comment by kevinkle** [comment]
Looks like https://github.com/superphy/backend/issues/159#issuecomment-314496516 works for storing the database in `/Warehouse`. But now need to network the docker composition to the blazegraph instance running on the host https://github.com/moby/moby/issues/1143#issuecomment-309952403 - doesn't look like there is an easy/Docker-approved method.

**Comment by kevinkle** [comment]
Implemented https://github.com/moby/moby/issues/1143#issuecomment-309952403 in our `docker-compose.yml` file:
From the comment:
```
version: '2'
services:
  <container_name>:
    image: <image_name>
    networks:
      - dockernet

networks:
  dockernet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1
```

except, we added to all our services:
```
networks:
      - dockernet
```
which still lets us use namespaces defined by docker (such as `redis`) to link containers, but we can also now run:

`curl http://192.168.0.1:9999/blazegraph/`

to connect to the blazegraph instance running on our host.
